server:
  port: 8081
  http2:
    enabled: true
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.12.203:13306/employees?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lkf.validation.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2.xml
debug: true
